version: "3"

networks:
  bid_managment:
    driver: bridge

services:
  app:
    build:
      args:
        user: pavel
        uid: 1000
      context: ./docker/php
      dockerfile: dockerfile
    image: bid_managment
    container_name: bid_managment-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./bid_managment:/var/www/html
    networks:
      - bid_managment
  redis:
    image: redis
    build: 
      context: ./docker/redis
      dockerfile: dockerfile
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - bid_managment
  mysql:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file:
      - ./docker/mysql/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "dbdata:/var/lib/mysql"
    networks:
      - bid_managment
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8888:8888
    volumes:
      - './bid_managment:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - bid_managment
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 1500:80
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_HOST=mysql
    networks:
      - bid_managment
volumes:
  dbdata:
    driver: local