version: "3"

networks:
  bid_managment:
    driver: bridge

services:
  app:
    build:
      args:
        user: pavel
        uid: 1000
      context: ./docker/php
      dockerfile: dockerfile
    image: bid_managment
    container_name: bid_managment-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./bid_managment:/var/www/html
    networks:
      - bid_managment
  db:
    image: mysql:8.0
    container_name: bid_managment-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "dbdata:/var/lib/mysql"
    networks:
      - bid_managment
  nginx:
    image: nginx:latest
    ports:
      - 8888:8888
    volumes:
      - './bid_managment:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - bid_managment
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 1500:80
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_HOST=mysql
    networks:
      - bid_managment
volumes:
  dbdata:
    driver: local